services:
  web:
    build:
      context: frontend
      args:
        VITE_API_URL: /api
    ports:
      - "80:80"

  api:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-product:/data/db
volumes:
  mongodb-product: